### ISSUE TITLE
Report into file

### ISSUE THREAD

**Issue by maharjanaman** [mlennox/eslint-complexity-checking#1]
Can we generate this report in a file or something?

**Comment by mlennox** [comment]
Thanks for the suggestion, I can look into doing that. 

I'm shortly going to investigate if I can turn this into an npm package so this can be added as a plugin/extension to the eslint config, so I may add the file output at that stage.

**Comment by mlennox** [comment]
@maharjanaman I have opened an issue to track this enhancement request in a new repo https://github.com/mlennox/eslint-formatter-complexity/issues/1

I'd welcome any comments you have there - thanks!

**Comment by mlennox** [comment]
@maharjanaman I've opened a second issue to track adding different output formats to the formatter https://github.com/mlennox/eslint-formatter-complexity/issues/2

**Comment by maharjanaman** [comment]
awesome

**Comment by mlennox** [comment]
closing this now as work will be done in https://github.com/mlennox/eslint-formatter-complexity please follow the issue there 👍
